[package]
edition = "2021"
name = "datafusion-catalogprovider-glue"
description = "Glue as a CatalogProvider for Datafusion"
version = "0.1.0"
homepage = "https://github.com/datafusion-contrib/datafusion-catalogprovider-glue"
repository = "https://github.com/datafusion-contrib/datafusion-catalogprovider-glue"
readme = "README.md"
authors = ["Tim Van Wassenhove <tim@timvw.be>"]
license = "Apache-2.0"
keywords = [ "arrow", "query", "sql", "datafusion", "aws", "glue" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "datafusion_catalogprovider_glue"
path = "src/lib.rs"

[dependencies]
arrow = { version = "14", features = ["prettyprint"] }
aws-config = "0.12.0"
aws-sdk-glue = "0.12.0"
aws-types = "0.12.0"
datafusion = "8.0.0"
datafusion-data-access = "8.0.0"
#datafusion-data-access = { git = "https://github.com/apache/arrow-datafusion" }
#datafusion-data-access = { path = "../arrow-datafusion/datafusion/data-access" }
#datafusion = { git = "https://github.com/apache/arrow-datafusion", features = ["avro"] }
datafusion-objectstore-s3 = { git = "https://github.com/timvw/datafusion-objectstore-s3", branch = "bump-to-datafusion-8" }
lazy_static = "1.4.0"
regex = "1"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "sync", "fs"] }

[dev-dependencies]
#datafusion = { path = "../arrow-datafusion/datafusion/core" }
