[package]
edition = "2021"
name = "datafusion-catalogprovider-glue"
description = "Glue as a CatalogProvider for Datafusion"
version = "0.1.0"
homepage = "https://github.com/datafusion-contrib/datafusion-catalogprovider-glue"
repository = "https://github.com/datafusion-contrib/datafusion-catalogprovider-glue"
readme = "README.md"
authors = ["Tim Van Wassenhove <tim@timvw.be>"]
license = "Apache-2.0"
keywords = [ "arrow", "datafusion", "aws", "glue" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "datafusion_catalogprovider_glue"
path = "src/lib.rs"

[dependencies]
aws-config = "0.12.0"
aws-sdk-glue = "0.12.0"
aws-types = "0.12.0"
datafusion = { version = "8.0.0", features = ["avro"] }
datafusion-objectstore-s3 = { version = "0.2.1" }
lazy_static = "1.4.0"
pest = "2.1"
pest_derive = "2.1"
regex = "1"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "sync", "fs"] }

