name: Publish artifacts

on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:

  publish_crate:
    name: Publish crate ${{ inputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_name }}
          submodules: true
      -
        name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
          default: true
      -
        name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}



            
